services:
  - type: web
    name: pluto
    runtime: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: GOOGLE_CLIENT_ID
        value: 922402174418-9vcvmgb1u6al78delh4u9j482ulrtqc2.apps.googleusercontent.com
      - key: ADMIN_EMAIL
        sync: false
      - key: DATABASE_URL
        sync: false
